Repository i3drobotics/phase-csharp, pull requests merged in 2022-09, with the labels that each got.

#21 Add ability to specify custom phase install location when building
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.yml
  README.md
  docs/doxygen/README_docs.md
  src/phasecsharp.csproj
Labels: enhancement

#22 remove prod merge into main after release
  .github/workflows/release.yml
Labels: bug

#23 update to phase v0.2.0
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/doxygen/README_docs.md
  release.md
Labels: enhancement

#25 clear changelog after release
  release.md
Labels: documentation, enhancement

#24 Seperate API version and project version
  src/phase/version.cs
  src/phasecsharp.csproj
Labels: enhancement

#27 Change phase version
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/doxygen/README_docs.md
  release.md
Labels: enhancement

#28 cleared unwanted header in demo list camera
  README.md
  src/phase/stereocamera/cameradeviceinfo.cs
  test/demo/demo_list_cameras/demo_list_cameras.cs
Labels: enhancement

#30 updated version to phase v0.3.0
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/doxygen/README_docs.md
  release.md
Labels: enhancement
